CREATE TABLE `users` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `sid` BIGINT(20) NULL DEFAULT NULL,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `money` DECIMAL(19,4) NULL DEFAULT NULL,
  `avatar` VARCHAR(2083) NULL DEFAULT NULL,
  `inv` VARCHAR(2083) NULL DEFAULT NULL,
  `trade` VARCHAR(2083) NULL DEFAULT NULL,
  `join` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `sid`)
);
